version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend-prod
    ports:
      - "8080:80"

  backend:
    build:
      context: ./backend
    container_name: backend-prod
    ports:
      - "5000:5000"