version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      target: dev      # Use the dev stage in Dockerfile
    container_name: frontend-dev
    ports:
      - "5173:5173"    # Host:Container
    volumes:
      - ./frontend:/app  # So changes on your host reflect inside container
    command: npm run dev

  backend:
    build:
      context: ./backend
      target: dev
    container_name: backend-dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: npm run start